### ISSUE TITLE
Set up testing.

### ISSUE THREAD

**Issue by jginsburgn** [google/semantic-locators#1]
Are there supposed to be testing toolings for this project?

**Comment by AlexLloyd0** [comment]
Thanks for the issues Jonathan :) I'll update the docs in the next few days. To run the karma test suite you can

```
cd javascript
yarn test
```

**Comment by AlexLloyd0** [comment]
Testing instructions can now be found in `DEVELOPMENT.md` files in the `javascript` and `webdriver_java` directories
