### ISSUE TITLE
Support iframe

### ISSUE THREAD

**Issue by icy0307** [google/semantic-locators#86]
**Describe the feature**
Please support semantic-locators works in iframe.
`accname` used to use `node instanceof HTMLElement`, that will not work on elements that belong to other windows/frames.
It seems that this problem got fixed, but never publish to npm?
https://github.com/google/accname/pull/75/commits/466d7e986fdddadbb21becd7f780e4a022fcc29a

**Use case**
I'm trying to add a custom command to cypress, and cypress runs everything inside an iframe

Awesome library. Thx. @AlexLloyd0

**Comment by AlexLloyd0** [comment]
Thanks for reporting this! I'm working on publishing a new accname release now, I'll update and release semantic locators next week :)

**Comment by AlexLloyd0** [comment]
2.1.0 is deployed to npm, Maven and pypi, which includes the latest version of Accname!
