### ISSUE TITLE
Question: how to select the first (or nth) match?

### ISSUE THREAD

**Issue by beck** [google/semantic-locators#92]
I currently have a failing test that uses semantic locators and the failure is:

> matched 2 elements, but expected to match 1

Is there a way to say take the first? Or n'th?

**Comment by beck** [comment]
This is not possible with how SL is currently spec'd.

**Comment by AlexLloyd0** [comment]
For anyone who finds this issue in the future:
This error message came from a framework which uses Semantic Locators.

- `findElementsBySemanticLocator` returns an array of all matching elements, which can be indexed like a normal array
- `findElementBySemanticLocator` returns the first matching element
